version: '3'
services:
  app:
    build: ./docker
    ports:
      - "8000:8000"
    volumes:
      - './:/app/'
    working_dir: '/app/'
    container_name: posefit-backend
    privileged: true
    tty: true