version: '3.8'
services:
  django:
    container_name: django
    build: ./django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./django/.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build: ./postgres
    volumes:
      - postgres_sample_data:/var/lib/postgresql/data
      - ./postgres/sql:/docker-entrypoint-initdb.d
    env_file: ./postgres/.env_db
    ports:
      - 5433:5432

volumes:
  postgres_sample_data: