@startuml

社内ユーザー -> 医療機器システム : 契約を作成する
社内ユーザー -> 医療機器システム : 施設を作成する
社内ユーザー -> 医療機器システム : スタッフを作成する
スタッフ -> 医療機器システム : ログインする
スタッフ -> 医療機器システム : スタッフ管理画面に遷移する
スタッフ -> 医療機器システム : スタッフの登録・更新等を行う

@enduml