# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'posefitMVP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMLKit/PoseDetection', '2.4.0'
  pod 'GoogleMLKit/PoseDetectionAccurate', '2.4.0'

  # Pods for posefitMVP

  target 'posefitMVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'posefitMVPUITests' do
    # Pods for testing
  end

end
