@startuml domain-model

package スタッフ管理 {
  class ユーザー
}

package 契約管理 {
  class 契約
}

package 施設管理 {
  class 施設
  class 建物
  class 部屋
}

package 医療機器管理 {
  class 医療機器
  class 医療機器個別詳細
  class 医療機器操作履歴
  class 点検履歴
  class 点検テンプレート
  class 点検テンプレート項目
  class 点検テンプレート項目の選択肢
  class 連絡先
}

package 研修管理 {
  class 研修会
  class 研修対象者
  class 研修項目
}

class 契約 {
  CeTraxを利用する企業や医療法人等
  ---
  名称
  契約開始日
  契約終了日
  契約ステータス
}

class 施設 {
  契約している法人が利用している施設
  ---
  名称
  認証コード
}
施設 "*" -- "1" 契約

class ユーザー {
  契約毎のログインユーザー（スタッフ）
  ---
  管理番号
  ログインID
  パスワード
  表示名
  職種
  ロール
}
ユーザー "*" -- "1" 施設

class 医療機器 {
  施設で管理している医療機器
  ---
  機器分類
  製品名
  承認番号
  耐用年数
  JANコード
  クラス分類
  設置管理区分
  特定保守管理区分
  定格電流
  薬事法承認番号
  保守点検名
  保守点検期間（月）
}
医療機器 "*" -- "1" 施設

class 医療機器個別詳細 {
  施設で管理している医療機器で個別に必要なもの
  ---
  管理番号
  製造番号
  最後に点検した日付
  購入価格
  納入日
  納入区分
  代理店
  製造販売業者
  契約終了日時
}
医療機器個別詳細 "*" -- "1" 施設
医療機器個別詳細 "*" -- "1" 医療機器

class 連絡先 {
  医療機器の連絡先
  ---
  アップロードした名刺ファイル
}
連絡先 "1" -- "1" 医療機器

class 建物 {
  施設の建物、病棟
  ---
  名称
}
建物 "*" -- "1" 施設

class 部屋 {
  施設の部屋、病室
  ---
  名称
}
部屋 "*" -- "1" 施設
部屋 "*" -- "1" 建物

class 医療機器操作履歴 {
  医療機器の貸出、移動、返却履歴
  ---
  操作日時
  アクション（貸出、返却、移動）
}
医療機器操作履歴 "*" -- "1" 医療機器個別詳細
医療機器操作履歴 "1" -- "1" ユーザー
医療機器操作履歴 "1" -- "1" 部屋

class 点検テンプレート {
  医療機器点検で利用する点検内容
  ---
  点検分類
}
点検テンプレート "1" -- "1" 医療機器個別詳細

class 点検テンプレート項目 {
  点検テンプレートの項目で、ラベルと入力形式を管理
  ---
  ラベル名
  入力形式
}
点検テンプレート項目 "*" -- "1" 点検テンプレート

class 点検テンプレート項目の選択肢 {
  点検テンプレート項目で入力形式がラジオボタン等の場合に使用する
  ---
  表示名
  キー
  バリュー
}
点検テンプレート項目の選択肢 "*" -- "1" 点検テンプレート項目

class 点検履歴 {
  医療機器の点検履歴で点検内容や日時等を保存する
  ---
  点検日時
  点検した人
  点検内容(json)
}
点検履歴 "*" -- "1" 医療機器個別詳細
点検履歴 "*" -- "1" ユーザー

class 研修会 {
  研修会
  ---
  名称
  研修日
  研修時間
  研修目的
  研修場所
  対象機器分類
  対象機器名
  添付資料
  備考
}
研修会 "*" -- "1" 施設
研修会 "*" -- "1" ユーザー

class 研修対象者 {
  研修会で必要な対象者
  ---
  対象者
}
研修対象者 "*" -- "1" 研修会

class 研修項目 {
  研修会で必要な対象者
  ---
  研修項目
}
研修項目 "*" -- "1" 研修会

@enduml