FROM ubuntu:22.04

SHELL ["/bin/bash", "-c"]

# python
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y python3.10 python3.10-dev \
    && source ~/.bashrc \
    && apt-get -y install vim netcat git

WORKDIR /usr/src/app

# environment vars
# avoid generating pyc files and writing to disc
ENV PYTHONDONTWRITEBYTECODE 1
# avoid buffering standard input / output
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

# install pip and dependencies
RUN apt-get install -y curl \
    && curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && apt-get install -y python3.10-distutils \
    && python3.10 get-pip.py \
    && pip install -U pip \
    && apt-get install -y build-essential libssl-dev libffi-dev libpq-dev libgdal-dev

# pipenv
RUN pip install pipenv
COPY Pipfile ./

# skip Pipfile.lock and install dependencies from Pipfile
RUN pipenv install --system --skip-lock --dev

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
COPY . /usr/src/app/

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
